version: '3.8'
services:
  # mscms:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   hostname: mscms
  #   container_name: mscms
  #   volumes:
  #     - .env:/var/www/html/.env:ro
  #   ports:
  #     - '21181:21181'
  #   environment:
  #     - APP_PORT=21181
  #     - APP_HOST="api.auxonode.com"
  #     - UID=1001
  #   networks:
  #     - coreSystemNetwork
  #   restart: unless-stopped
  #   depends_on:
  #     - redisCoreSystem

  redisCoreSystem:
    hostname: redisCoreSystem
    container_name: redisCoreSystem
    image: redis:alpine3.16
    ports:
      - '21179:6379'
    volumes:
      - redisVolumes:/data
    networks:
      - coreSystemNetwork
    restart: unless-stopped
    depends_on:
      - dBCoreSystem

  dBCoreSystem:
    hostname: dBCoreSystem
    container_name: dBCoreSystem
    image: postgres:14-alpine
    ports:
      - '21132:5432'
    environment:
      - POSTGRES_PASSWORD=testing123
      - POSTGRES_USER=admin123
      - POSTGRES_DB=laravel
    volumes:
      - dbVolumes:/var/lib/postgresql/data
    networks:
      - coreSystemNetwork
    restart: unless-stopped

  mariaDB:
    image: mariadb:10.3.37
    ports:
      - '21106:3306'
    volumes:
      - mariaDBVolumes:/var/lib/mysql
    networks:
      - coreSystemNetwork
    environment:
      MARIADB_ROOT_PASSWORD: testing123
      MARIADB_DATABASE: mscms

networks:
  coreSystemNetwork:
    name: coreSystemNetwork
    driver: bridge

volumes:
  dbVolumes:
    driver: local
  redisVolumes:
    driver: local
  mariaDBVolumes:
    driver: local
